name: Build microADB

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake

    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake .. \
        -DADBD_TCP_SERVER_PORT=5555 \
        -DADBD_AUTHENTICATION=ON \
        -DADBD_AUTH_PUBKEY=ON \
        -DADBD_FILE_SERVICE=ON \
        -DADBD_CNXN_PAYLOAD_SIZE="1024" \
        -DADBD_PAYLOAD_SIZE="64" \
        -DADBD_FRAME_MAX="1" \
        -DADBD_TOKEN_SIZE="20" \
        -DADBD_DEVICE_ID="\"abcd\"" \
        -DADBD_PRODUCT_NAME="\"adb_dev\"" \
        -DADBD_PRODUCT_MODEL="\"adb_board\"" \
        -DADBD_PRODUCT_DEVICE="\"NuttX_device\"" \
        -DADBD_FEATURES="\"cmd\""

    - name: Build
      run: |
        cmake --build build
